svn-all-fast-export/svn2git

src/svn.cpp
Sometimes some revisions are filtered out by authz rules on the server,
and when you create a mirror with svnsync, you end up with an empty
revision that has no revprops whatsoever.  This means svnlog, svndate
and svnauthor are all NULL.  This used to cause segfaults.
Here's some context: http://svn.haxx.se/users/archive-2013-02/0160.shtml
=> Handle revisions with no revprops

src/svn.cpp
When converting the MacPorts Subversion repository to Git, the conversion fails at revision 8:
```
Exporting revision 8 svn: E160013: File not found: revision 8, path '/trunk/base/Tcl/pkgIndex.tcl'
```
I'm not sure whether the offending call to `svn_fs_copied_from` worked in earlier versions of Subversion. For the record, my copy was built against Subversion 1.9.2. My solution for the problem is not calling `svn_fs_copied_from` for deleted files (because their history must obviously be where they are deleted anyway, you cannot (or can you, but why would you) copy a file and delete it in the same commit).
=> svn.cpp: Do not call svn_fs_copied_from on delete

src/main.cpp, src/repository.cpp, src/repository.h, src/ruleparser.cpp
The change 4686434f149a7c6c3f6aef6f0d9f394990bc87db breaks the functionality of
~~~
create repository foo
repository bar
prefix baz/
end repository
~~~
Which should forward stuff that is attributed to repository `foo` to repository `bar` instead with a prefix of `baz/`.
Now the `prefix` rule is ignored and the `repository` rules value is taken as prefix which does not make too much sense and breaks the functionality of those rules that was intended with commit
008b28e0f4c48de8d740c51c053020d1a36315bf.
This PR tries to fix this behaviour to get the original meaning of the rules back.
=> Make 'repository' and 'prefix' inside 'repository' work like expected again

src/svn.cpp
Despite the comment on the `continue` line, it makes not sense to check this here.
In the iteration below is made sure that directories get a slash appended in the end and that if no rule matched **and** it is a directory, the recursion goes on in the subdirectory.
With the lines I removed, the recursion doesn't consider the file entries and so you cannot match single files in a recursed directory.
=> When recursing into a directory, also match files, not only directories

src/ruleparser.cpp, src/ruleparser.h
Before it was sorted by string representation which does not sort numbers correctly, but put 10 between 1 and 2.
=> Output the rules ordered by filename and linenumber when using --stats

src/repository.cpp
Expand the size of marks to 64bits.
This fixes some wrap issues with very large
repositories.
It's possible the issue was more with the use
of int vers unsigned int but just go to 64bits to
make sure there are no problems.
Fix the MAX mark macro as that was actually
going one beyond max int (1 << 32) will overflow
an int.
=> make sure we have enough space for marks

src/main.cpp, src/svn.cpp
Support for importing empty directories in Git, see issue #15.
=> Support for importing empty directories

src/svn.cpp
Useful for Debian jessie (https://packages.debian.org/jessie/subversion), Ubuntu Trusty LTS (https://launchpad.net/ubuntu/+source/subversion) and maybe others.
=> Allow compiling against SVN 1.8.

src/repository.cpp
This fixes a problem on platforms where git automatically defaults to
case-insensitive repositories (e.g. OS X and Windows), where case-only
renames would be simply ignored.
This would turn SVN changes such as https://trac.macports.org/changeset/153824/trunk/dports into empty Git commits when exported on an OS X machine.
=> Always mark repositories case-sensitive

README.md
```
root@bc1d5718a270:/sync# apt-get install build-essential subversion git qtchooser qt-qmake qt5-default libapr1 libapr1-dev libsvn-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt-qmake
```
`qt-qmake` already contains in `qt5-default` package.
=> Fixed package install command for Ubuntu into README file.

src/svn.cpp
Use-Case: Explicitly matching a subpath inside a repository for ignore or moving to another repository like that:
```
match /trunk/project/bigdir/
action ignore
end match
match /trunk/project/
repository trunk/project.git
branch master
end match
```
Problem: When there is a change to /trunk/project/ (e.g. changing a property), recursiveDumpDir always dumped the complete subpath to the parent repo, ignoring the rules of subpaths.
This pull request implements rule matching also for recursiveDumpDir.
=> Fixed ignoring of subpaths inside a repository

src/repository.cpp, src/svn.cpp
- fix for #34, also porting svn:global-ignores to .gitignore and correctly transform SVN ignore patterns to Git ignore patterns
- fix for a typo
- do not warn about svn:mergeinfo when warning about unknown SVN properties
=> Overhauling .gitignore file generation

src/repository.cpp, src/svn.cpp
If you have a rule that matches a file, not a directory and use the `--svn-branches` parameter, svn2git tries to recursively dump the file which of course gives an error from SVN that the file is not a directory. Actually I find it even worse that svn2git just ignores the error and goes on without the file. Anyway, I fixed the routine to just dump the blob if it is not a directory.
=> Various improvements (was: "Do not try to recursively dump a file")

src/main.cpp, src/repository.cpp
Very large SVN repositories, especially those which include binary
files, tend to result in very large git pack files (tens of gigabytes).
With its current approach, svn2git will wait 30 seconds (the default
timeout of waitForFinished()) for git fast-import to finish before it
terminates the git process. That default timeout is way too small for
large pack files for which the import process can take several minutes.
To work around this very long processing time, this commit adds the new
command line option "--fast-import-timeout". It allows the user to set a
custom timeout in seconds to wait for git fast-import to finish, with a
timeout of 0 meaning that svn2git will wait forever. This way even large
SVN repositories can be imported successfully.
=> Make git fast-import timeout configurable (#39)

src/src.pro
=> Fix evaluation of emptyness of SVN_LIBDIR that sometimes always gives false, sometime always true, but never what is intended

src/svn.cpp
Path replacements did not work properly
- if `--empty-dirs` is used, old files were not cleaned out but survived
- if `--svn-ignore` is used and the path_from has svn:ignore, then the target path did not get a `.gitignore` file
This fixes #43 and is an alternative approach to #62 which tries to solve the first point, but at an earlier `--empty-dirs`-independent place.
I think this fix is the better one as it fixes the actually broken `--empty-dirs` implementation.
=> Fix Path Replacements

src/repository.cpp, src/repository.h, src/svn.cpp
If you have a ref name refs/tags/foo you cannot create a ref refs/tags/foo/bar
and also the other way around, as for the former a file and the the latter a directory
would be created that both would be named 'foo' as long as the refs are not packed.
So check for this and abort early so that the rules can be adapted to produce proper names.
=> Abort on conflicting ref names

src/repository.cpp
- Automatically adds a trailing '/' to match patterns if the user forgets, but warns them,
- Doesn't issue the "branch does not exist" error for revnum 1 :)
=> Minor QoL changes

src/svn.cpp
I'm constrained to 1.6 here, and needed this patch only.
=> Use svn_repos_open() for Subversion 1.6

src/svn.cpp, test/copy-directories.bats, test/empty-dirs.bats, test/svn-ignore.bats
Before this PR a directory was recursively dumped if one of the mentioned parameters was used,
in addition to being dumped because the file is listed separately in the change.
=> Do not dump added directories multiple times if svn-properties or empty-dirs is used

src/svn.cpp, test/empty-dirs.bats
This is a rebase of #89 by @mbaschnitzi (thanks) onto latest master and adds tests for the bug / use-case.
This obsoletes #89.
=> Fix missing .gitignore in empty dirs on dir rename

test.sh, test/empty-dirs.bats
=> Fail test execution if there were duplicate test names (#106)

README.md
are to be found after the conversion.
=> Fix some typos in the README and add a pointer to where annotated tags

src/repository.cpp
- Instead of master use the `init.defaultBranch`
if set.
=> Support git default branch name

src/repository.cpp, src/repository.h
Error our if import process errors.
Might happen if pipe problems happen with fast-import etc...
=> Error out if error happens in fast import process

src/repository.cpp
Fix for strange warning:
Warnings appears if revision 1 does not contain the default branch yet, but revision 2 first creates it.
Thanks for merging.
=> Do not warn the user if default branch does not exist

README.md
So far only a note in the Readme:
I was searching for the code to fix this "end slash" issue.
But could not find the correct place yet. Could that be fixed by removing all front slashes `/myfile.txt` just before sending it to `git fast-import`, shouldn't that work?
Thansk for merging.
=> Notes on end slash requirement

.github/workflows/build.yaml, Dockerfile
The current Dockerfile is failing `docker build`:
```
W: GPG error: http://deb.debian.org/ jessie-updates InRelease: The following signatures were invalid: KEYEXPIRED 1668891673
W: GPG error: http://deb.debian.org/ jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673
```
https://github.com/TWiStErRob/svn2git/actions/runs/4282343577/jobs/7456498595
=> Update Dockerfile and CI it

.github/workflows/build.yaml, src/CommandLineParser.cpp, src/main.cpp, src/repository.cpp, src/ruleparser.cpp, src/ruleparser.h, src/src.pro, src/svn.cpp
Fixes #163
Please note that:
- I have not migrated off of class `QRegExp` because successor `QRegularExpression` has a different pattern syntax and so backwards compatibility would be broken e.g. with regard to existing rules files. That migration should probably be a distinct future pull request and come with a bump in major version to signal its breaking nature.
- While I have applied care here, true C++ is not my day-to-day language so this should be reviewed carefully before merging. Thanks in advance!
- If this gets merged, please do not squash-merge but preserve the commit cut lines that have been chosen carefully. Thank you!
=> Support both Qt 5 and Qt 6 at the same time (fixes #163)

samples/ignore-branch.rules, samples/merged-branches-tags.rules, samples/min-max-revision.rules, samples/recurse.rules, samples/standardlayout.rules, samples/two-projects.rules
=> `samples`: Replace branch `master` by `main` (fixes #160)
